---
- name: "Automating docker file"
  hosts: localhost
  tasks:
    - name: stop running container
      command: docker stop python-app
      ignore_errors: yes
    
    - name: remove stoped container
      command: docker rm python-app
      ignore_errors: yes
    
    - name: remove old image
      command: docker rmi python-img
      ignore_errors: yes

    - name: build new image
      command: docker build -t python-img .

    - name: run new container 
      command: docker run -d --name python-app -p 5000:5000 python-img:latest
      